server {
    listen 80;
    server_name _;
    root /usr/share/nginx/html;
    index index.html;
    add_header X-Content-Type-Options "nosniff" always;
    add_header Referrer-Policy "strict-origin-when-cross-origin" always;
    add_header X-Frame-Options "DENY" always;
    add_header X-Robots-Tag "noindex, nofollow" always;

    location = / {
        add_header Cache-Control "no-store, must-revalidate" always;
        add_header X-Frame-Options "DENY" always;
        add_header X-Robots-Tag "noindex, nofollow" always;
        expires -1;
        try_files /index.html =404;
    }
    location ~* \.html$ {
        add_header Cache-Control "no-store, must-revalidate" always;
        add_header Pragma "no-cache" always;
        add_header X-Frame-Options "DENY" always;
        add_header X-Robots-Tag "noindex, nofollow" always;
        expires -1;
    }
    location ~* \.(jpg|jpeg|png|webp|svg|otf|ttf|woff2?|mp3|ico)$ {
        add_header Cache-Control "no-cache" always;
        etag on;
    }
    location / { try_files $uri $uri/ /index.html; }
}
